# Generated by Django 3.1.1 on 2020-10-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0003_auto_20201010_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(max_length=50),
        ),
    ]
