# Generated by Django 3.1.1 on 2020-10-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0006_auto_20201010_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
