# Generated by Django 3.1.1 on 2020-10-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0008_user_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
