# Generated by Django 3.1.1 on 2020-10-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0010_user_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_status',
            field=models.BooleanField(default=False),
        ),
    ]
