# Generated by Django 3.1.1 on 2020-10-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0011_auto_20201012_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
