# Generated by Django 3.1.1 on 2020-10-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0012_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=7),
        ),
    ]
