# Generated by Django 3.1.1 on 2020-10-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0013_auto_20201013_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not', 'Not to Mention')], max_length=7),
        ),
    ]
