# Generated by Django 3.1.1 on 2020-10-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='service',
        ),
    ]
