# Generated by Django 3.1.1 on 2020-10-18 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0002_auto_20201011_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subservice', models.CharField(max_length=35)),
                ('price', models.FloatField(max_length=5)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmodule.service')),
            ],
        ),
    ]
