# Generated by Django 3.1.1 on 2020-10-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0003_subservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subservice',
            old_name='subservice',
            new_name='sub_service',
        ),
    ]
