# Generated by Django 3.1.1 on 2020-10-12 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staffmodule', '0002_auto_20201011_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_on', models.DateField()),
                ('delivery_type', models.CharField(choices=[('local', 'Local Picked Up'), ('myself', 'myself')], max_length=30)),
                ('status', models.CharField(choices=[('pickedup', 'Picked Up'), ('canceled', 'Canceled'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='pickedup', max_length=20)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('delivered_on', models.DateTimeField(blank=True, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cid', to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(to='staffmodule.Service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
