# Generated by Django 3.1.1 on 2020-10-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cid',
            new_name='cust_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_type',
            field=models.CharField(choices=[('local', 'Local Picked Up'), ('myself', 'My self')], max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pickedup', 'Picked Up'), ('canceled', 'Canceled'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
