# Generated by Django 3.1.1 on 2020-10-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_auto_20201012_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='staff',
            new_name='assigned_staff',
        ),
        migrations.AddField(
            model_name='booking',
            name='load_type',
            field=models.CharField(blank=True, choices=[('bag', 'Bag'), ('dress', 'Dress')], max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='unit',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
