# Generated by Django 3.1.1 on 2020-10-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0005_auto_20201013_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='unit',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='load_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_on',
        ),
    ]
