# Generated by Django 3.1.1 on 2020-10-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0006_auto_20201018_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='delivered_on',
        ),
    ]
