# Generated by Django 3.1.1 on 2020-10-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0008_auto_20201018_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Pickup (Self)'), ('door-step', 'Door Step')], max_length=30),
        ),
    ]
