# Generated by Django 3.1.1 on 2020-10-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0004_auto_20201018_1227'),
        ('laundry', '0009_auto_20201018_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='sub_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffmodule.subservice'),
        ),
    ]
