# Generated by Django 3.1.1 on 2020-10-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0010_booking_sub_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cleaning', 'Cleaning'), ('pickedup', 'Picked Up'), ('canceled', 'Canceled'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
