# Generated by Django 3.1.1 on 2020-10-22 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0004_auto_20201018_1227'),
        ('laundry', '0013_auto_20201022_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmodule.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sub_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmodule.subservice'),
        ),
    ]
